# Generated by Django 3.1.4 on 2021-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfname', models.CharField(max_length=100)),
                ('cuname', models.CharField(max_length=100)),
                ('cphone', models.IntegerField(max_length=100)),
                ('cemail', models.CharField(max_length=100)),
                ('caddress', models.TextField(max_length=100)),
                ('cpassword', models.CharField(max_length=100)),
            ],
        ),
    ]
