# Generated by Django 3.1.4 on 2021-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=120)),
                ('address', models.TextField(max_length=200)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_email', models.CharField(max_length=90)),
                ('account_number', models.CharField(max_length=20)),
                ('current_balance', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
